# Generated by Django 5.2.5 on 2026-02-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('ela_image', models.ImageField(blank=True, null=True, upload_to='ela_outputs/')),
                ('prediction', models.CharField(choices=[('Authentic', 'Authentic'), ('Tampered', 'Tampered')], max_length=10)),
                ('tamper_score', models.FloatField(help_text='Ensemble tamper probability (0–1)')),
                ('cnn_prob', models.FloatField(default=0.0)),
                ('svm_prob', models.FloatField(default=0.0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
